fix-datetime64
opensearch-project/opensearch-py-ml pull request #342
Opened 2023-11-13 20:17 UTC by Prikshit7766

### Description
[Describe what this change achieves]
 - #338 
### Issues Resolved
[List any issues this PR will resolve]
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2023-11-15 06:11 UTC, rawwar commented on noxfile.py
> +    session.run("python", "-m", "pip", "install", "-r", "requirements.txt")
Do we need this?   we are already installing `requirements-dev.txt` in the previous line.

2023-11-15 06:13 UTC, rawwar commented on noxfile.py
> +    session.run("python", "-m", "pip", "install", "-r", "requirements.txt")
Do we need this? we are installing requirements on line 145

2023-11-15 06:13 UTC, rawwar commented on noxfile.py
> +    session.run("python", "-m", "pip", "install", "-r", "requirements.txt")
Do we need this?   we are already installing `requirements-dev.txt` in the previous line.

2023-11-15 06:16 UTC, rawwar requested changes
made few comments. please look into them.

2023-11-15 06:55 UTC, Prikshit7766 commented
@rawwar 
Thanks for reviewing the code. I have updated some of the things that you have suggested. 
let me know if there is anything else.

2023-11-15 06:57 UTC, dhrubo-os commented
DCO is missing. Can you please fix the DCO?

2023-11-15 07:57 UTC, Prikshit7766 commented
@dhrubo-os 
let me know if it works !!

2023-11-15 09:51 UTC, rawwar commented
@Prikshit7766 , If you did the sign off correctly, you would see the DCO check passing.  DCO check will mention the commits which are not signed off. So you should be able to verify by yourself next time.

2023-11-15 15:40 UTC, Prikshit7766 commented
@rawwar 
thanks!! 
I think now DCO check is passing

2023-11-16 01:07 UTC, rawwar commented
@Prikshit7766 , Quick question. The issue you linked is only to remove fix the data type. You also included updating the nox tests. Any reason for that?

2023-11-16 19:52 UTC, Prikshit7766 commented
I have updated ci.yml for installing the requirements.txt. which will install the pandas version mentioned in the requirements.txt.
let me know if it works ?

2023-11-16 20:07 UTC, rawwar commented
> I have updated ci.yml for installing the requirements.txt. which will install the pandas version mentioned in the requirements.txt. let me know if it works ?

That's not the fix actually. But, can you just revert those nox related changes and just push the datatype issue? We can take up that nox related one on a separate PR. Also, please run a test locally. You can do it by running `nox -s test` . Make sure to have a opensearch instance running on localhost.

2023-11-16 20:29 UTC, Prikshit7766 commented
I will close this PR and create a new one

2023-11-16 20:29 UTC, closed without merging